### ISSUE TITLE
Compilling error

### ISSUE THREAD

**Issue by alexe100** [ojousima/ojousima.logger.c#1]
(Ubuntu)
I have a folder with these sub folders:

nRF5_SDK_15.2.0_9412b96
ojousima.logger.c

Then, using SES I open app from 

ojousima.logger.c/targets/ruuvitag_b/ses/ojousima.logger.c.emProject

When I click build:

Compiling 'nrf_log_backend_serial.c'
   nrf_log_backend_serial.c
      sdk_config.h: file or folder does not exists

Thanks
Alex

**Comment by ojousima** [comment]
Have you run `git submodule update --init --recursive`?

**Comment by alexe100** [comment]
I did this:

cd Test
git clone https://github.com/ojousima/ojousima.logger.c.git
cd ojousima.logger.c/
git submodule update --init --recursive
I opnened SES and opnened project: 
... ojousima.logger.c/targets/ruuvitag_b/ses/ojousima.logger.c.emProject
Build:
sdk_config.h: file or folder does not exists


Inside ojousima.logger.c folder I did:
$find . -iname 'sdk_config.h'

but no file was found

Please, help

**Comment by ojousima** [comment]
The file is under ruuvi.drivers.c/nrf5_sdk15_platform,
https://github.com/ojousima/ruuvi.drivers.c/tree/9901d62410913ff8533d5d07f56ce2c055a834b6/nrf5_sdk15_platform . 
Which version of SES you're on? I'm on SES Nordic version 4.16. Nordic variants of SES are a bit tricky to find, the nRF Connect Getting started assistant has links. Generic version of SES should be ok for nRF SDK projects too, though. 

Can you join Ruuvi Slack at slack.ruuvi.com and ping me (ojousima) there?

**Comment by alexe100** [comment]
Here is my SES about info:

EGGER Embedded Studio for ARM
Release 4.16  Build 2019032803.38728
Linux x64
© 2014-2019 SEGGER Microcontroller GmbH
© 1997-2019 Rowley Associates Ltd.
GCC/BINUTILS: Built using the GNU ARM Embedded Toolchain version 8-2018-q4-major source distribution
Clang/LLVM: Built using the version 7.0.1 source distribution

---------------------------------------------------------------------------------------------------
After execute all the commands, the drivers directory remains empty! Also the ojousima.ruuvi_endpoints.c folder remains empty too.

Well, I filled all the sub folders by hand and now the compiler errors due to lack of files desapear. However, now I have this error when compiling with SES:

incompatible types when assigning to type ‘ruuvi_interface_gpio_id_t’ {aka ‘union <anonymous>’} from type ‘short unsigned int’

This error is due to this code line:

config.mosi = RUUVI_BOARD_SPI_MOSI_PIN; 

on tasks_spi.c

Thanks

**Comment by alexe100** [comment]
Ficheiro ou directoria inexistente => File not found

**Comment by alexe100** [comment]
Please, can you share complete project source code ready to compile. Thanks

**Comment by ojousima** [comment]
The reason why project uses submodules is that it has a snapshot of compatible projects, such as board and driver definitions. If you populate the submodules by hand with latest files it's easy to get errors as above. 

The root issue is that for some reason the submodules do not get downloaded when you run the submodule update command. 

Can you provide exact log of the commands and output you get when you clone the project? Here's mine:
```
Last login: Sat Jul  6 18:16:03 on ttys005
Otso-MacBook-Pro:~ otsojousimaa$ mkdir demo
Otso-MacBook-Pro:~ otsojousimaa$ cd demo/
Otso-MacBook-Pro:demo otsojousimaa$ git clone https://github.com/ojousima/ojousima.logger.c.git
Cloning into 'ojousima.logger.c'...
remote: Enumerating objects: 1232, done.
remote: Total 1232 (delta 0), reused 0 (delta 0), pack-reused 1232
Receiving objects: 100% (1232/1232), 245.57 KiB | 683.00 KiB/s, done.
Resolving deltas: 100% (749/749), done.
Otso-MacBook-Pro:demo otsojousimaa$ git branch -a
fatal: not a git repository (or any of the parent directories): .git
Otso-MacBook-Pro:demo otsojousimaa$ cd ojousima.logger.c/
Otso-MacBook-Pro:ojousima.logger.c otsojousimaa$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/acceleration-broadcaster
  remotes/origin/acceleration_broadcaster
  remotes/origin/acceleration_broadcaster_v1
  remotes/origin/acceleration_streamer
  remotes/origin/ext-bme
  remotes/origin/fast-v2
  remotes/origin/master
  remotes/origin/ruuviblog
Otso-MacBook-Pro:ojousima.logger.c otsojousimaa$ git checkout acceleration_streamer
Branch 'acceleration_streamer' set up to track remote branch 'acceleration_streamer' from 'origin'.
Switched to a new branch 'acceleration_streamer'
Otso-MacBook-Pro:ojousima.logger.c otsojousimaa$ git submodule update --init --recursive
Submodule 'ruuvi.boards.c' (https://github.com/ruuvi/ruuvi.boards.c.git) registered for path 'ruuvi.boards.c'
Submodule 'ruuvi.drivers.c' (https://github.com/ojousima/ruuvi.drivers.c.git) registered for path 'ruuvi.drivers.c'
Submodule 'ruuvi.endpoints.c' (https://github.com/ruuvi/ruuvi.endpoints.c) registered for path 'ruuvi.endpoints.c'
Submodule 'ruuvi.libraries.c' (https://github.com/ruuvi/ruuvi.libraries.c) registered for path 'ruuvi.libraries.c'
Cloning into '/Users/otsojousimaa/demo/ojousima.logger.c/ruuvi.boards.c'...
Cloning into '/Users/otsojousimaa/demo/ojousima.logger.c/ruuvi.drivers.c'...
Cloning into '/Users/otsojousimaa/demo/ojousima.logger.c/ruuvi.endpoints.c'...
Cloning into '/Users/otsojousimaa/demo/ojousima.logger.c/ruuvi.libraries.c'...
Submodule path 'ruuvi.boards.c': checked out '6a874f9fe5fbf820c5f8c57ea7ec3287501d8fb7'
Submodule path 'ruuvi.drivers.c': checked out '2ac466617741eeec5471c9e7189907bccb0a45d8'
Submodule 'BME280_driver' (https://github.com/BoschSensortec/BME280_driver.git) registered for path 'ruuvi.drivers.c/BME280_driver'
Submodule 'STMems_Standard_C_drivers' (https://github.com/STMicroelectronics/STMems_Standard_C_drivers) registered for path 'ruuvi.drivers.c/STMems_Standard_C_drivers'
Cloning into '/Users/otsojousimaa/demo/ojousima.logger.c/ruuvi.drivers.c/BME280_driver'...
Cloning into '/Users/otsojousimaa/demo/ojousima.logger.c/ruuvi.drivers.c/STMems_Standard_C_drivers'...
Submodule path 'ruuvi.drivers.c/BME280_driver': checked out '18260d616b8c03fc1c4e1d68bed578c4605d40b4'
Submodule path 'ruuvi.drivers.c/STMems_Standard_C_drivers': checked out 'a306f351b4ceba8766581433c3e98fab7905f806'
Submodule path 'ruuvi.endpoints.c': checked out 'd4a54668ad08b69f5d79577c64735ad370941c1c'
Submodule path 'ruuvi.libraries.c': checked out '719e9d673b339ac6018820c08235ef5c1ebc9f87'
Otso-MacBook-Pro:ojousima.logger.c otsojousimaa$ cd ..
Otso-MacBook-Pro:demo otsojousimaa$ ln -s /Users/otsojousimaa/git/nRF5_SDK_15.2.0_9412b96 nRF5_SDK_15.2.0_9412b96
Otso-MacBook-Pro:demo otsojousimaa$ ls -l
total 0
lrwxr-xr-x   1 otsojousimaa  staff   47  7 Hei 10:24 nRF5_SDK_15.2.0_9412b96 -> /Users/otsojousimaa/git/nRF5_SDK_15.2.0_9412b96
drwxr-xr-x  18 otsojousimaa  staff  576  7 Hei 10:22 ojousima.logger.c
```
And the project compiles with
```
SEGGER Embedded Studio for ARM
Release 4.16  Build 2019032803.38728
macOS x64

© 2014-2019 SEGGER Microcontroller GmbH
© 1997-2019 Rowley Associates Ltd.

GCC/BINUTILS: Built using the GNU ARM Embedded Toolchain version 8-2018-q4-major source distribution

Clang/LLVM: Built using the version 7.0.1 source distribution
```
At least in Debug-configuration

**Comment by alexe100** [comment]
user1@user1-PORTEGE-Z930:~/Imagens$ git clone https://github.com/ojousima/ojousima.logger.c.git
Cloning into 'ojousima.logger.c'...
remote: Enumerating objects: 1232, done.
remote: Total 1232 (delta 0), reused 0 (delta 0), pack-reused 1232
Receiving objects: 100% (1232/1232), 245.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (749/749), done.
Checking connectivity... done.

user1@user1-PORTEGE-Z930:~/Imagens$ cd ojousima.logger.c/

user1@user1-PORTEGE-Z930:~/Imagens/ojousima.logger.c$ git submodule update --init --recursive

Submodule 'ojousima.ruuvi_endpoints.c' (https://github.com/ojousima/ojousima.ruuvi_endpoints.c.git) registered for path 'ojousima.ruuvi_endpoints.c'
Submodule 'ruuvi.boards.c' (https://github.com/ruuvi/ruuvi.boards.c.git) registered for path 'ruuvi.boards.c'
Submodule 'ruuvi.drivers.c' (https://github.com/ojousima/ruuvi.drivers.c.git) registered for path 'ruuvi.drivers.c'
Submodule 'ruuvi.endpoints.c' (https://github.com/ruuvi/ruuvi.endpoints.c) registered for path 'ruuvi.endpoints.c'
Submodule 'ruuvi.libraries.c' (https://github.com/ruuvi/ruuvi.libraries.c) registered for path 'ruuvi.libraries.c'
Cloning into 'ojousima.ruuvi_endpoints.c'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 35 (delta 19), reused 24 (delta 12), pack-reused 0
Unpacking objects: 100% (35/35), done.
Checking connectivity... done.
fatal: reference is not a tree: 6b090d80fd4dbdc7a1d68b786b6317aef0e2e817
Cloning into 'ruuvi.boards.c'...
remote: Enumerating objects: 105, done.
remote: Total 105 (delta 0), reused 0 (delta 0), pack-reused 105
Receiving objects: 100% (105/105), 14.75 KiB | 0 bytes/s, done.
Resolving deltas: 100% (63/63), done.
Checking connectivity... done.
Caminho do sub-módulo 'ruuvi.boards.c': confirmado '83940399838e2e4434bad82ac975be1ef9be2b8e'
Cloning into 'ruuvi.drivers.c'...
remote: Enumerating objects: 1756, done.
remote: Total 1756 (delta 0), reused 0 (delta 0), pack-reused 1756
Receiving objects: 100% (1756/1756), 477.81 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1104/1104), done.
Checking connectivity... done.
fatal: reference is not a tree: 9901d62410913ff8533d5d07f56ce2c055a834b6
Cloning into 'ruuvi.endpoints.c'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 64 (delta 0), reused 2 (delta 0), pack-reused 61
Unpacking objects: 100% (64/64), done.
Checking connectivity... done.
Caminho do sub-módulo 'ruuvi.endpoints.c': confirmado '96fe4ebe6abcfaa99ea3da14680450548826096c'
Cloning into 'ruuvi.libraries.c'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 64 (delta 4), reused 7 (delta 3), pack-reused 51
Unpacking objects: 100% (64/64), done.
Checking connectivity... done.
Caminho do sub-módulo 'ruuvi.libraries.c': confirmado 'c68b8cf8377dd4816ef918e4606664f8c0dec911'
Impossível confirmar '6b090d80fd4dbdc7a1d68b786b6317aef0e2e817' no caminho do sub-módulo 'ojousima.ruuvi_endpoints.c'
Impossível confirmar '9901d62410913ff8533d5d07f56ce2c055a834b6' no caminho do sub-módulo 'ruuvi.drivers.c'

**Comment by ojousima** [comment]
Ok, Here's the issue:
`fatal: reference is not a tree: 9901d62410913ff8533d5d07f56ce2c055a834b6` I've probably not pushed something to GitHub. Let me check...

**Comment by ojousima** [comment]
You're missing the `git checkout acceleration_streamer` at the start, master is something I'm constantly working on and broken quite often. You should get a compilable project with the acceleration_streamer branch, remember to update the modules after checking it out. 

We're also working on GATT on official Ruuvi repository, but that's also pre-alpha and broken often.

**Comment by alexe100** [comment]
Sorry, I did not see any ref to execute git checkout acceleration_streamer
Now it compiles.
Thank you

**Comment by ojousima** [comment]
Ok, happy to hear that it worked.
